//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algorithms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Algorithms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59
        ///73 41
        ///52 40 09
        ///26 53 06 34
        ///10 51 87 86 81
        ///61 95 66 57 25 68
        ///90 81 80 38 92 67 73
        ///30 28 51 76 81 18 75 44
        ///84 14 95 87 62 81 17 78 58
        ///21 46 71 58 02 79 62 39 31 09
        ///56 34 35 53 78 31 81 18 90 93 15
        ///78 53 04 21 84 93 32 13 97 11 37 51
        ///45 03 81 79 05 18 78 86 13 30 63 99 95
        ///39 87 96 28 03 38 42 17 82 87 58 07 22 57
        ///06 17 51 17 07 93 09 07 75 97 95 78 87 08 53
        ///67 66 59 60 88 99 94 65 55 77 55 34 27 53 78 28
        ///76 40 41 04 87 16 09 42 75 69 23 97 30 60 10 79 87
        ///12 10 44 26 21 36 32 84 98 60 13 12  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _67Triangle {
            get {
                return ResourceManager.GetString("_67Triangle", resourceCulture);
            }
        }
    }
}
