using System;
using System.Collections.Generic;
using System.Text;

namespace Algorithms.ProjectEuler
{
    public static class _2EvenFibonacciNumbers
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        //By starting with 1 and 2, the first 10 terms will be:

        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        public static int Execute()
        {
            //Calculated ignoring odd terms
            var maxVal = 4000000;

            int x = 1, y = 1, sum = 0;

            while (x < maxVal)
            {
                var currentX = x;
                sum += x + y;
                x = x + 2 * y;
                y = 2 * currentX + 3 * y;
            }

            return sum;
        }

        /// <summary>
        /// Brute forcing it
        /// </summary>
        /// <returns></returns>
        public static int FirstRun()
        {
            const int maxVal = 4000000;
            int val = 1, previousVal = 1, sum = 0;

            while (val < maxVal)
            {
                var instanceVal = val;
                if (val % 2 == 0) sum += val;
                val += previousVal;
                previousVal = instanceVal;
            }

            return sum;
        }
    }
}
